# Generated by Django 4.1.1 on 2022-09-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numdos", models.CharField(max_length=8, unique=True)),
                ("numdos_vl", models.CharField(blank=True, max_length=8, null=True)),
                ("ancart", models.CharField(blank=True, max_length=25, null=True)),
                ("channel", models.CharField(blank=True, max_length=3, null=True)),
                ("stage", models.FloatField(blank=True, null=True)),
                ("ve", models.CharField(blank=True, max_length=3, null=True)),
                ("format", models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
