# Generated by Django 4.1.1 on 2022-09-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_support"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standard",
            name="format",
        ),
    ]
